dubbo:
  application:
    name: dubbo-provider
    qos-enable: true
  scan:
    # 接口扫描路径
    base-packages: com.yide.service2
  protocol:
    name: dubbo
    # -1 代表自动分配端口
    port: 20881
    # 配置高速序列化规则
    serialization: kryo
  registry:
    # 服务注册地址，也就是 Nacos 的服务器地址
    address: nacos://localhost:8848
  provider:
    # 配置负载均衡策略（轮询）
    loadbalance: roundrobin
server:
  port: 8092